development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  reconnect: false
  pool: 5
  database: turbulent-duck-chat
  username: root
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: production
  pool: 5
  username: root
  password: